name: Sync JotForm to Notion

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes UTC
  workflow_dispatch:        # Manual trigger via GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv requests

      - name: Run main.py
        env:
          JOTFORM_API_KEY: ${{ secrets.JOTFORM_API_KEY }}
          JOTFORM_ID: ${{ secrets.JOTFORM_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py
